# Starship Configuration with Catppuccin Theme

format = """
[](#cba6f7)\
$os\
$username\
[](bg:#89b4fa fg:#cba6f7)\
$directory\
[](fg:#89b4fa bg:#74c7ec)\
$git_branch\
$git_status\
[](fg:#74c7ec bg:#94e2d5)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#94e2d5 bg:#f9e2af)\
$docker_context\
[](fg:#f9e2af bg:#f38ba8)\
$time\
[ ](fg:#f38ba8)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "bg:#cba6f7"
style_root = "bg:#cba6f7"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#cba6f7"
disabled = true

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "bg:#89b4fa"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#f9e2af"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#74c7ec"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#74c7ec"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#94e2d5"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#f38ba8"
format = '[ ♥ $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:#a6e3a1)'
error_symbol = '[](bold fg:#f38ba8)'
vimcmd_symbol = '[](bold fg:#a6e3a1)'
vimcmd_replace_one_symbol = '[](bold fg:#cba6f7)'
vimcmd_replace_symbol = '[](bold fg:#cba6f7)'
vimcmd_visual_symbol = '[](bold fg:#f9e2af)'
